spring:
  application:
    name: youlai-boot
  profiles:
    active: dev
  config:
    import: classpath:codegen.yml
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
# banner.txt에 프로젝트 버전 표시, @project.version@을 사용하여 pom.xml에서 가져옴
project:
  version: @project.version@
