# "youlai-boot"라는 이름의 브리지 네트워크 생성, 동일한 네트워크의 컨테이너는 컨테이너명을 통해 서로 접근 가능
networks:
  youlai-boot:
    driver: bridge

services:
  mysql:
    image: mysql:8.0.29
    container_name: mysql
    restart: unless-stopped # 재시작 정책: 수동으로 중지하지 않는 한 자동 재시작
    environment:
      - TZ=Asia/Shanghai
      - LANG= en_US.UTF-8
      - MYSQL_ROOT_PASSWORD=123456 # root 사용자의 비밀번호 설정
    volumes:
      - ./mysql/conf/my.cnf:/etc/my.cnf # my.cnf 파일을 컨테이너의 지정 경로에 마운트
      - ./mysql/data:/var/lib/mysql # MySQL 데이터 영구 저장
      - ../sql/mysql:/docker-entrypoint-initdb.d # SQL 스크립트 초기화 디렉토리
    ports:
      - 3306:3306
    networks:
      - youlai-boot # "youlai-boot" 네트워크에 가입

  redis:
    image: redis:7.2.3
    container_name: redis
    restart: unless-stopped
    command: redis-server /etc/redis/redis.conf --requirepass 123456 --appendonly no # Redis 서비스 시작 및 비밀번호 123456 추가, 기본적으로 Redis AOF 방식 영구 저장 설정 비활성화
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./redis/data:/data
      - ./redis/config/redis.conf:/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - youlai-boot

  minio:
    image: minio/minio:RELEASE.2024-07-16T23-46-41Z
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    networks:
      - youlai-boot

  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.4.0
    container_name: xxl-job-admin
    restart: unless-stopped
    environment:
      PARAMS: '--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=root --spring.datasource.password=123456 --spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver'
    volumes:
      - ./xxljob/logs:/data/applogs
    ports:
      - 8080:8080
    networks:
      - youlai-boot
